[theme]
base = "light"
primaryColor = "#147d86"
backgroundColor = "#f5f7fb"
secondaryBackgroundColor = "#eaf0f5"
textColor = "#142b43"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"
headless = true
